id: P003117
initial_creation_type: ocr
source_metadata:
  id: bdr:W19822
  title: པོ་ཏ་ལར་བཞུགས་པའི་རྙིང་མའི་གསུང་འབུམ་དཀར་ཆག
  author: ''
  volumes:
    4a3e7292fa7447be82906527296529b0:
      image_group_id: I1PD27435
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
