id: I4EDD3DAE
legacy_id: P003117
ocr_import_info:
  bdrc_scan_id: W19822
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T18:53:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:40:14.447170+00:00'
last_modified: 2022-08-30 23:40:49.128422
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19822
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19822
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: པོ་ཏ་ལར་བཞུགས་པའི་རྙིང་མའི་གསུང་འབུམ་དཀར་ཆག
  author: དོམ་པོ་བ་ཐུབ་བསྟན་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9143650196014613
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD27435:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD27435
      total_pages: 518
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD27435.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9143650196014613
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
