id: I4EDD3DAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:56:24+00:00'
last_modified: '2022-06-07T17:42:29.379734+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19822
  title: པོ་ཏ་ལར་བཞུགས་པའི་རྙིང་མའི་གསུང་འབུམ་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    67A4:
      image_group_id: I1PD27435
      title: ''
      total_pages: 518
      order: 1
      base_file: 67A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
